/* automatically generated from xfwm4-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (xfwm4_dialog_ui)
#endif
#ifdef __GNUC__
static const char xfwm4_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char xfwm4_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\"?><interface><object class=\"GtkAdjustment\" id=\""
  "adjustment1\"><property name=\"value\">5</property><property name=\"low"
  "er\">5</property><property name=\"upper\">2000</property><property name"
  "=\"step_increment\">1</property><property name=\"page_increment\">10</p"
  "roperty></object><object class=\"GtkAdjustment\" id=\"adjustment2\"><pr"
  "operty name=\"value\">5</property><property name=\"lower\">5</property>"
  "<property name=\"upper\">2000</property><property name=\"step_increment"
  "\">1</property><property name=\"page_increment\">10</property></object>"
  "<object class=\"GtkAdjustment\" id=\"adjustment3\"><property name=\"val"
  "ue\">20</property><property name=\"lower\">5</property><property name=\""
  "upper\">100</property><property name=\"step_increment\">1</property><pr"
  "operty name=\"page_increment\">10</property></object><object class=\"Gt"
  "kAdjustment\" id=\"adjustment4\"><property name=\"value\">20</property>"
  "<property name=\"lower\">5</property><property name=\"upper\">100</prop"
  "erty><property name=\"step_increment\">1</property><property name=\"pag"
  "e_increment\">10</property></object><object class=\"XfceTitledDialog\" "
  "id=\"main-dialog\"><property name=\"title\" translatable=\"yes\">Window"
  " Manager</property><property name=\"window_position\">center-on-parent<"
  "/property><property name=\"icon_name\">xfwm4</property><property name=\""
  "type_hint\">dialog</property><property name=\"subtitle\" translatable=\""
  "yes\">Configure window behavior and shortcuts</property><child internal"
  "-child=\"vbox\"><object class=\"GtkVBox\" id=\"main-vbox\"><property na"
  "me=\"visible\">True</property><property name=\"orientation\">vertical</"
  "property><child><object class=\"GtkNotebook\" id=\"plug-child\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">True</p"
  "roperty><property name=\"border_width\">6</property><child><object clas"
  "s=\"GtkHBox\" id=\"hbox7\"><property name=\"visible\">True</property><p"
  "roperty name=\"border_width\">12</property><property name=\"spacing\">1"
  "2</property><child><object class=\"GtkFrame\" id=\"frame13\"><property "
  "name=\"visible\">True</property><property name=\"label_xalign\">0</prop"
  "erty><property name=\"shadow_type\">none</property><child><object class"
  "=\"GtkAlignment\" id=\"alignment11\"><property name=\"visible\">True</p"
  "roperty><property name=\"top_padding\">6</property><property name=\"lef"
  "t_padding\">12</property><child><object class=\"GtkScrolledWindow\" id="
  "\"scrolledwindow3\"><property name=\"width_request\">200</property><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">True"
  "</property><property name=\"hscrollbar_policy\">automatic</property><pr"
  "operty name=\"vscrollbar_policy\">automatic</property><property name=\""
  "shadow_type\">in</property><child><object class=\"GtkTreeView\" id=\"th"
  "eme_name_treeview\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">True</property><property name=\"headers_visible\">F"
  "alse</property></object></child></object></child></object></child><chil"
  "d type=\"label\"><object class=\"GtkLabel\" id=\"label32\"><property na"
  "me=\"visible\">True</property><property name=\"label\" translatable=\"y"
  "es\">&lt;b&gt;_Theme&lt;/b&gt;</property><property name=\"use_markup\">"
  "True</property><property name=\"use_underline\">True</property></object"
  "></child></object><packing><property name=\"position\">0</property></pa"
  "cking></child><child><object class=\"GtkVBox\" id=\"vbox12\"><property "
  "name=\"visible\">True</property><property name=\"orientation\">vertical"
  "</property><property name=\"spacing\">6</property><child><object class="
  "\"GtkFrame\" id=\"frame10\"><property name=\"visible\">True</property><"
  "property name=\"label_xalign\">0</property><property name=\"shadow_type"
  "\">none</property><child><object class=\"GtkAlignment\" id=\"alignment1"
  "4\"><property name=\"visible\">True</property><property name=\"border_w"
  "idth\">6</property><property name=\"bottom_padding\">6</property><prope"
  "rty name=\"left_padding\">12</property><child><object class=\"GtkFontBu"
  "tton\" id=\"title_font_button\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">True</property><property name=\"receive"
  "s_default\">True</property></object></child></object></child><child typ"
  "e=\"label\"><object class=\"GtkLabel\" id=\"label23\"><property name=\""
  "visible\">True</property><property name=\"label\" translatable=\"yes\">"
  "&lt;b&gt;Title fon_t&lt;/b&gt;</property><property name=\"use_markup\">"
  "True</property><property name=\"use_underline\">True</property><propert"
  "y name=\"mnemonic_widget\">title_font_button</property></object></child"
  "></object><packing><property name=\"expand\">False</property><property "
  "name=\"fill\">False</property><property name=\"position\">0</property><"
  "/packing></child><child><object class=\"GtkFrame\" id=\"frame11\"><prop"
  "erty name=\"visible\">True</property><property name=\"label_xalign\">0<"
  "/property><property name=\"shadow_type\">none</property><child><object "
  "class=\"GtkAlignment\" id=\"title_align_box\"><property name=\"visible\""
  ">True</property><property name=\"border_width\">6</property><property n"
  "ame=\"bottom_padding\">6</property><property name=\"left_padding\">12</"
  "property><child><object class=\"GtkComboBox\" id=\"title_align_combo\">"
  "<property name=\"visible\">True</property></object></child></object></c"
  "hild><child type=\"label\"><object class=\"GtkLabel\" id=\"label24\"><p"
  "roperty name=\"visible\">True</property><property name=\"label\" transl"
  "atable=\"yes\">&lt;b&gt;Title _alignment&lt;/b&gt;</property><property "
  "name=\"use_markup\">True</property><property name=\"use_underline\">Tru"
  "e</property><property name=\"mnemonic_widget\">title_align_combo</prope"
  "rty></object></child></object><packing><property name=\"expand\">False<"
  "/property><property name=\"fill\">False</property><property name=\"posi"
  "tion\">1</property></packing></child><child><object class=\"GtkFrame\" "
  "id=\"frame12\"><property name=\"visible\">True</property><property name"
  "=\"label_xalign\">0</property><property name=\"shadow_type\">none</prop"
  "erty><child><object class=\"GtkAlignment\" id=\"button_layout_box\"><pr"
  "operty name=\"visible\">True</property><property name=\"bottom_padding\""
  ">6</property><property name=\"left_padding\">12</property><child><objec"
  "t class=\"GtkVBox\" id=\"vbox13\"><property name=\"visible\">True</prop"
  "erty><property name=\"border_width\">6</property><property name=\"orien"
  "tation\">vertical</property><property name=\"spacing\">6</property><chi"
  "ld><object class=\"GtkLabel\" id=\"label26\"><property name=\"visible\""
  ">True</property><property name=\"xalign\">0</property><property name=\""
  "label\" translatable=\"yes\">Click and drag the buttons to change the l"
  "ayout</property></object><packing><property name=\"position\">0</proper"
  "ty></packing></child><child><object class=\"GtkFrame\" id=\"active-fram"
  "e\"><property name=\"visible\">True</property><property name=\"label_xa"
  "lign\">0</property><property name=\"shadow_type\">in</property><child><"
  "object class=\"GtkAlignment\" id=\"alignment17\"><property name=\"visib"
  "le\">True</property><property name=\"border_width\">6</property><child>"
  "<object class=\"GtkHBox\" id=\"active-box\"><property name=\"height_req"
  "uest\">26</property><property name=\"visible\">True</property><child><o"
  "bject class=\"GtkButton\" id=\"button-layout-|\"><property name=\"label"
  "\" translatable=\"yes\">Title</property><property name=\"visible\">True"
  "</property><property name=\"can_focus\">True</property><property name=\""
  "receives_default\">True</property><property name=\"tooltip_text\" trans"
  "latable=\"yes\">The window title cannot be removed</property></object><"
  "packing><property name=\"expand\">False</property><property name=\"fill"
  "\">False</property><property name=\"position\">0</property></packing></"
  "child></object></child></object></child><child type=\"label\"><object c"
  "lass=\"GtkLabel\" id=\"label27\"><property name=\"visible\">True</prope"
  "rty><property name=\"label\" translatable=\"yes\">Active</property><pro"
  "perty name=\"use_markup\">True</property></object></child></object><pac"
  "king><property name=\"position\">1</property></packing></child><child><"
  "object class=\"GtkFrame\" id=\"hidden-frame\"><property name=\"visible\""
  ">True</property><property name=\"label_xalign\">0</property><property n"
  "ame=\"shadow_type\">in</property><child><object class=\"GtkAlignment\" "
  "id=\"alignment18\"><property name=\"visible\">True</property><property "
  "name=\"border_width\">6</property><child><object class=\"GtkHBox\" id=\""
  "hidden-box\"><property name=\"height_request\">26</property><property n"
  "ame=\"visible\">True</property><property name=\"spacing\">5</property><"
  "child><object class=\"GtkButton\" id=\"button-layout-O\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">True</property"
  "><property name=\"receives_default\">True</property><property name=\"to"
  "oltip_text\" translatable=\"yes\">Menu</property><child><object class=\""
  "GtkImage\" id=\"image1\"><property name=\"visible\">True</property><pro"
  "perty name=\"stock\">gtk-index</property></object></child></object><pac"
  "king><property name=\"expand\">False</property><property name=\"fill\">"
  "False</property><property name=\"position\">0</property></packing></chi"
  "ld><child><object class=\"GtkButton\" id=\"button-layout-T\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">True</prop"
  "erty><property name=\"receives_default\">True</property><property name="
  "\"tooltip_text\" translatable=\"yes\">Stick</property><child><object cl"
  "ass=\"GtkImage\" id=\"image2\"><property name=\"visible\">True</propert"
  "y><property name=\"stock\">gtk-add</property></object></child></object>"
  "<packing><property name=\"expand\">False</property><property name=\"fil"
  "l\">False</property><property name=\"position\">1</property></packing><"
  "/child><child><object class=\"GtkButton\" id=\"button-layout-S\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">True</"
  "property><property name=\"receives_default\">True</property><property n"
  "ame=\"tooltip_text\" translatable=\"yes\">Shade</property><child><objec"
  "t class=\"GtkImage\" id=\"image3\"><property name=\"visible\">True</pro"
  "perty><property name=\"stock\">gtk-goto-top</property></object></child>"
  "</object><packing><property name=\"expand\">False</property><property n"
  "ame=\"fill\">False</property><property name=\"position\">2</property></"
  "packing></child><child><object class=\"GtkButton\" id=\"button-layout-H"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">True</property><property name=\"receives_default\">True</property><p"
  "roperty name=\"tooltip_text\" translatable=\"yes\">Hide</property><chil"
  "d><object class=\"GtkImage\" id=\"image4\"><property name=\"visible\">T"
  "rue</property><property name=\"stock\">gtk-undo</property></object></ch"
  "ild></object><packing><property name=\"expand\">False</property><proper"
  "ty name=\"fill\">False</property><property name=\"position\">3</propert"
  "y></packing></child><child><object class=\"GtkButton\" id=\"button-layo"
  "ut-M\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">True</property><property name=\"receives_default\">True</propert"
  "y><property name=\"tooltip_text\" translatable=\"yes\">Maximize</proper"
  "ty><child><object class=\"GtkImage\" id=\"image5\"><property name=\"vis"
  "ible\">True</property><property name=\"stock\">gtk-zoom-100</property><"
  "/object></child></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">False</property><property name=\"position\""
  ">4</property></packing></child><child><object class=\"GtkButton\" id=\""
  "button-layout-C\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">True</property><property name=\"receives_default\">Tr"
  "ue</property><property name=\"tooltip_text\" translatable=\"yes\">Close"
  "</property><child><object class=\"GtkImage\" id=\"image6\"><property na"
  "me=\"visible\">True</property><property name=\"stock\">gtk-close</prope"
  "rty></object></child></object><packing><property name=\"expand\">False<"
  "/property><property name=\"fill\">False</property><property name=\"posi"
  "tion\">5</property></packing></child></object></child></object></child>"
  "<child type=\"label\"><object class=\"GtkLabel\" id=\"label28\"><proper"
  "ty name=\"visible\">True</property><property name=\"label\" translatabl"
  "e=\"yes\">Hidden</property><property name=\"use_markup\">True</property"
  "></object></child></object><packing><property name=\"position\">2</prop"
  "erty></packing></child></object></child></object></child><child type=\""
  "label\"><object class=\"GtkLabel\" id=\"label25\"><property name=\"visi"
  "ble\">True</property><property name=\"label\" translatable=\"yes\">&lt;"
  "b&gt;Button layout&lt;/b&gt;</property><property name=\"use_markup\">Tr"
  "ue</property></object></child></object><packing><property name=\"expand"
  "\">False</property><property name=\"fill\">False</property><property na"
  "me=\"position\">2</property></packing></child></object><packing><proper"
  "ty name=\"position\">1</property></packing></child></object></child><ch"
  "ild type=\"tab\"><object class=\"GtkLabel\" id=\"label1\"><property nam"
  "e=\"visible\">True</property><property name=\"label\" translatable=\"ye"
  "s\">_Style</property><property name=\"use_underline\">True</property></"
  "object><packing><property name=\"tab_fill\">False</property></packing><"
  "/child><child><object class=\"GtkFrame\" id=\"frame9\"><property name=\""
  "visible\">True</property><property name=\"border_width\">12</property><"
  "property name=\"label_xalign\">0</property><property name=\"shadow_type"
  "\">none</property><child><object class=\"GtkAlignment\" id=\"alignment1"
  "2\"><property name=\"visible\">True</property><property name=\"border_w"
  "idth\">6</property><property name=\"left_padding\">12</property><child>"
  "<object class=\"GtkVBox\" id=\"vbox10\"><property name=\"visible\">True"
  "</property><property name=\"orientation\">vertical</property><property "
  "name=\"spacing\">6</property><child><object class=\"GtkScrolledWindow\""
  " id=\"scrolledwindow2\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">True</property><property name=\"hscrollbar_poli"
  "cy\">never</property><property name=\"vscrollbar_policy\">automatic</pr"
  "operty><property name=\"shadow_type\">in</property><child><object class"
  "=\"GtkTreeView\" id=\"shortcuts_treeview\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">True</property></object></ch"
  "ild></object><packing><property name=\"position\">0</property></packing"
  "></child><child><object class=\"GtkHButtonBox\" id=\"hbuttonbox1\"><pro"
  "perty name=\"visible\">True</property><property name=\"spacing\">12</pr"
  "operty><property name=\"layout_style\">center</property><child><object "
  "class=\"GtkButton\" id=\"shortcuts_clear_button\"><property name=\"labe"
  "l\">gtk-clear</property><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">True</property><property name=\"receives_defaul"
  "t\">True</property><property name=\"use_stock\">True</property></object"
  "><packing><property name=\"expand\">False</property><property name=\"fi"
  "ll\">False</property><property name=\"position\">0</property></packing>"
  "</child><child><object class=\"GtkButton\" id=\"shortcuts_reset_button\""
  "><property name=\"label\" translatable=\"yes\">_Reset to Defaults</prop"
  "erty><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">True</property><property name=\"receives_default\">True</property>"
  "<property name=\"use_underline\">True</property></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">False</pro"
  "perty><property name=\"pack_type\">end</property><property name=\"posit"
  "ion\">1</property></packing></child></object><packing><property name=\""
  "expand\">False</property><property name=\"position\">1</property></pack"
  "ing></child></object></child></object></child><child type=\"label\"><ob"
  "ject class=\"GtkLabel\" id=\"label22\"><property name=\"visible\">True<"
  "/property><property name=\"label\" translatable=\"yes\">&lt;b&gt;Window"
  " _shortcuts&lt;/b&gt;</property><property name=\"use_markup\">True</pro"
  "perty><property name=\"use_underline\">True</property></object></child>"
  "</object><packing><property name=\"position\">1</property></packing></c"
  "hild><child type=\"tab\"><object class=\"GtkLabel\" id=\"label2\"><prop"
  "erty name=\"visible\">True</property><property name=\"label\" translata"
  "ble=\"yes\">Ke_yboard</property><property name=\"use_underline\">True</"
  "property></object><packing><property name=\"position\">1</property><pro"
  "perty name=\"tab_fill\">False</property></packing></child><child><objec"
  "t class=\"GtkVBox\" id=\"vbox7\"><property name=\"visible\">True</prope"
  "rty><property name=\"border_width\">12</property><property name=\"orien"
  "tation\">vertical</property><property name=\"spacing\">6</property><chi"
  "ld><object class=\"GtkFrame\" id=\"frame5\"><property name=\"visible\">"
  "True</property><property name=\"label_xalign\">0</property><property na"
  "me=\"shadow_type\">none</property><child><object class=\"GtkAlignment\""
  " id=\"alignment7\"><property name=\"visible\">True</property><property "
  "name=\"border_width\">6</property><property name=\"bottom_padding\">6</"
  "property><property name=\"left_padding\">12</property><child><object cl"
  "ass=\"GtkVBox\" id=\"vbox14\"><property name=\"visible\">True</property"
  "><property name=\"orientation\">vertical</property><property name=\"spa"
  "cing\">6</property><child><object class=\"GtkHBox\" id=\"hbox3\"><prope"
  "rty name=\"visible\">True</property><property name=\"spacing\">12</prop"
  "erty><property name=\"homogeneous\">True</property><child><object class"
  "=\"GtkRadioButton\" id=\"click_to_focus_radio\"><property name=\"label\""
  " translatable=\"yes\">Clic_k to focus</property><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">True</property><propert"
  "y name=\"receives_default\">False</property><property name=\"use_underl"
  "ine\">True</property><property name=\"draw_indicator\">True</property><"
  "/object><packing><property name=\"position\">0</property></packing></ch"
  "ild><child><object class=\"GtkRadioButton\" id=\"focus_follows_mouse_ra"
  "dio\"><property name=\"label\" translatable=\"yes\">Focus follows _mous"
  "e</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">False</p"
  "roperty><property name=\"use_underline\">True</property><property name="
  "\"draw_indicator\">True</property><property name=\"group\">click_to_foc"
  "us_radio</property></object><packing><property name=\"position\">1</pro"
  "perty></packing></child></object><packing><property name=\"position\">0"
  "</property></packing></child><child><object class=\"GtkLabel\" id=\"lab"
  "el29\"><property name=\"visible\">True</property><property name=\"xalig"
  "n\">0</property><property name=\"label\" translatable=\"yes\">_Delay be"
  "fore window receives focus:</property><property name=\"use_markup\">Tru"
  "e</property><property name=\"use_underline\">True</property><property n"
  "ame=\"mnemonic_widget\">focus_delay_scale</property></object><packing><"
  "property name=\"position\">1</property></packing></child><child><object"
  " class=\"GtkAlignment\" id=\"alignment19\"><property name=\"visible\">T"
  "rue</property><property name=\"left_padding\">12</property><child><obje"
  "ct class=\"GtkHBox\" id=\"focus_delay_hbox\"><property name=\"visible\""
  ">True</property><property name=\"spacing\">12</property><child><object "
  "class=\"GtkLabel\" id=\"label30\"><property name=\"visible\">True</prop"
  "erty><property name=\"label\" translatable=\"yes\" comments=\"Focus del"
  "ay\">&lt;i&gt;Short&lt;/i&gt;</property><property name=\"use_markup\">T"
  "rue</property></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"fill\">False</property><property name=\"position\">"
  "0</property></packing></child><child><object class=\"GtkHScale\" id=\"f"
  "ocus_delay_scale\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">True</property><property name=\"update_policy\">disc"
  "ontinuous</property><property name=\"adjustment\">adjustment1</property"
  "><property name=\"draw_value\">False</property></object><packing><prope"
  "rty name=\"position\">1</property></packing></child><child><object clas"
  "s=\"GtkLabel\" id=\"label31\"><property name=\"visible\">True</property"
  "><property name=\"label\" translatable=\"yes\" comments=\"Focus delay\""
  ">&lt;i&gt;Long&lt;/i&gt;</property><property name=\"use_markup\">True</"
  "property></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">False</property><property name=\"position\">2</pr"
  "operty></packing></child></object></child></object><packing><property n"
  "ame=\"position\">2</property></packing></child></object></child></objec"
  "t></child><child type=\"label\"><object class=\"GtkLabel\" id=\"label15"
  "\"><property name=\"visible\">True</property><property name=\"label\" t"
  "ranslatable=\"yes\">&lt;b&gt;Focus model&lt;/b&gt;</property><property "
  "name=\"use_markup\">True</property></object></child></object><packing><"
  "property name=\"expand\">False</property><property name=\"fill\">False<"
  "/property><property name=\"position\">0</property></packing></child><ch"
  "ild><object class=\"GtkFrame\" id=\"frame6\"><property name=\"visible\""
  ">True</property><property name=\"label_xalign\">0</property><property n"
  "ame=\"shadow_type\">none</property><child><object class=\"GtkAlignment\""
  " id=\"alignment8\"><property name=\"visible\">True</property><property "
  "name=\"border_width\">6</property><property name=\"bottom_padding\">6</"
  "property><property name=\"left_padding\">12</property><child><object cl"
  "ass=\"GtkCheckButton\" id=\"focus_new_check\"><property name=\"label\" "
  "translatable=\"yes\">Automatically give focus to _newly created windows"
  "</property><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">True</property><property name=\"receives_default\">False</pr"
  "operty><property name=\"use_underline\">True</property><property name=\""
  "draw_indicator\">True</property></object></child></object></child><chil"
  "d type=\"label\"><object class=\"GtkLabel\" id=\"label16\"><property na"
  "me=\"visible\">True</property><property name=\"label\" translatable=\"y"
  "es\">&lt;b&gt;New window focus&lt;/b&gt;</property><property name=\"use"
  "_markup\">True</property></object></child></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">False</property>"
  "<property name=\"position\">1</property></packing></child><child><objec"
  "t class=\"GtkFrame\" id=\"frame7\"><property name=\"visible\">True</pro"
  "perty><property name=\"label_xalign\">0</property><property name=\"shad"
  "ow_type\">none</property><child><object class=\"GtkAlignment\" id=\"ali"
  "gnment9\"><property name=\"visible\">True</property><property name=\"bo"
  "rder_width\">6</property><property name=\"bottom_padding\">6</property>"
  "<property name=\"left_padding\">12</property><child><object class=\"Gtk"
  "VBox\" id=\"vbox8\"><property name=\"visible\">True</property><property"
  " name=\"orientation\">vertical</property><property name=\"spacing\">6</"
  "property><child><object class=\"GtkCheckButton\" id=\"raise_on_focus_ch"
  "eck\"><property name=\"label\" translatable=\"yes\">Automatically _rais"
  "e windows when they receive focus</property><property name=\"visible\">"
  "True</property><property name=\"can_focus\">True</property><property na"
  "me=\"receives_default\">False</property><property name=\"use_underline\""
  ">True</property><property name=\"draw_indicator\">True</property></obje"
  "ct><packing><property name=\"position\">0</property></packing></child><"
  "child><object class=\"GtkVBox\" id=\"vbox9\"><property name=\"visible\""
  ">True</property><property name=\"orientation\">vertical</property><prop"
  "erty name=\"spacing\">6</property><child><object class=\"GtkLabel\" id="
  "\"label19\"><property name=\"visible\">True</property><property name=\""
  "xalign\">0</property><property name=\"label\" translatable=\"yes\">Dela"
  "y _before raising focused window:</property><property name=\"use_underl"
  "ine\">True</property><property name=\"mnemonic_widget\">focus_raise_del"
  "ay_scale</property></object><packing><property name=\"expand\">False</p"
  "roperty><property name=\"fill\">False</property><property name=\"positi"
  "on\">0</property></packing></child><child><object class=\"GtkAlignment\""
  " id=\"alignment1\"><property name=\"visible\">True</property><property "
  "name=\"left_padding\">12</property><child><object class=\"GtkHBox\" id="
  "\"hbox4\"><property name=\"visible\">True</property><property name=\"sp"
  "acing\">12</property><child><object class=\"GtkLabel\" id=\"label20\"><"
  "property name=\"visible\">True</property><property name=\"label\" trans"
  "latable=\"yes\" comments=\"Raise focus delay\">&lt;i&gt;Short&lt;/i&gt;"
  "</property><property name=\"use_markup\">True</property></object><packi"
  "ng><property name=\"expand\">False</property><property name=\"fill\">Fa"
  "lse</property><property name=\"position\">0</property></packing></child"
  "><child><object class=\"GtkHScale\" id=\"focus_raise_delay_scale\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">True"
  "</property><property name=\"update_policy\">discontinuous</property><pr"
  "operty name=\"adjustment\">adjustment2</property><property name=\"draw_"
  "value\">False</property></object><packing><property name=\"position\">1"
  "</property></packing></child><child><object class=\"GtkLabel\" id=\"lab"
  "el21\"><property name=\"visible\">True</property><property name=\"label"
  "\" translatable=\"yes\" comments=\"Raise focus delay\">&lt;i&gt;Long&lt"
  ";/i&gt;</property><property name=\"use_markup\">True</property></object"
  "><packing><property name=\"expand\">False</property><property name=\"fi"
  "ll\">False</property><property name=\"position\">2</property></packing>"
  "</child></object></child></object><packing><property name=\"position\">"
  "1</property></packing></child></object><packing><property name=\"positi"
  "on\">1</property></packing></child></object></child></object></child><c"
  "hild type=\"label\"><object class=\"GtkLabel\" id=\"label17\"><property"
  " name=\"visible\">True</property><property name=\"label\" translatable="
  "\"yes\">&lt;b&gt;Raise on focus&lt;/b&gt;</property><property name=\"us"
  "e_markup\">True</property></object></child></object><packing><property "
  "name=\"expand\">False</property><property name=\"fill\">False</property"
  "><property name=\"position\">2</property></packing></child><child><obje"
  "ct class=\"GtkFrame\" id=\"frame8\"><property name=\"visible\">True</pr"
  "operty><property name=\"label_xalign\">0</property><property name=\"sha"
  "dow_type\">none</property><child><object class=\"GtkAlignment\" id=\"al"
  "ignment10\"><property name=\"visible\">True</property><property name=\""
  "border_width\">6</property><property name=\"bottom_padding\">6</propert"
  "y><property name=\"left_padding\">12</property><child><object class=\"G"
  "tkCheckButton\" id=\"raise_on_click_check\"><property name=\"label\" tr"
  "anslatable=\"yes\">Raise window when clicking _inside application windo"
  "w</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">False</p"
  "roperty><property name=\"use_underline\">True</property><property name="
  "\"draw_indicator\">True</property></object></child></object></child><ch"
  "ild type=\"label\"><object class=\"GtkLabel\" id=\"label18\"><property "
  "name=\"visible\">True</property><property name=\"label\" translatable=\""
  "yes\">&lt;b&gt;Raise on click&lt;/b&gt;</property><property name=\"use_"
  "markup\">True</property></object></child></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">False</property><"
  "property name=\"position\">3</property></packing></child></object><pack"
  "ing><property name=\"position\">2</property></packing></child><child ty"
  "pe=\"tab\"><object class=\"GtkLabel\" id=\"label3\"><property name=\"vi"
  "sible\">True</property><property name=\"label\" translatable=\"yes\">_F"
  "ocus</property><property name=\"use_underline\">True</property></object"
  "><packing><property name=\"position\">2</property><property name=\"tab_"
  "fill\">False</property></packing></child><child><object class=\"GtkVBox"
  "\" id=\"vbox1\"><property name=\"visible\">True</property><property nam"
  "e=\"border_width\">12</property><property name=\"orientation\">vertical"
  "</property><property name=\"spacing\">6</property><child><object class="
  "\"GtkFrame\" id=\"frame1\"><property name=\"visible\">True</property><p"
  "roperty name=\"label_xalign\">0</property><property name=\"shadow_type\""
  ">none</property><child><object class=\"GtkAlignment\" id=\"alignment2\""
  "><property name=\"visible\">True</property><property name=\"border_widt"
  "h\">6</property><property name=\"bottom_padding\">6</property><property"
  " name=\"left_padding\">12</property><child><object class=\"GtkVBox\" id"
  "=\"vbox2\"><property name=\"visible\">True</property><property name=\"o"
  "rientation\">vertical</property><property name=\"spacing\">6</property>"
  "<child><object class=\"GtkCheckButton\" id=\"snap_to_border_check\"><pr"
  "operty name=\"label\" translatable=\"yes\">Snap windows to screen _bord"
  "er</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">False</p"
  "roperty><property name=\"use_underline\">True</property><property name="
  "\"draw_indicator\">True</property></object><packing><property name=\"ex"
  "pand\">False</property><property name=\"fill\">False</property><propert"
  "y name=\"position\">0</property></packing></child><child><object class="
  "\"GtkCheckButton\" id=\"snap_to_window_check\"><property name=\"label\""
  " translatable=\"yes\">Snap windows to other _windows</property><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">True</pr"
  "operty><property name=\"receives_default\">False</property><property na"
  "me=\"use_underline\">True</property><property name=\"draw_indicator\">T"
  "rue</property></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"fill\">False</property><property name=\"position\">"
  "1</property></packing></child><child><object class=\"GtkVBox\" id=\"vbo"
  "x5\"><property name=\"visible\">True</property><property name=\"orienta"
  "tion\">vertical</property><property name=\"spacing\">6</property><child"
  "><object class=\"GtkLabel\" id=\"label9\"><property name=\"visible\">Tr"
  "ue</property><property name=\"xalign\">0</property><property name=\"lab"
  "el\" translatable=\"yes\">Dis_tance:</property><property name=\"use_und"
  "erline\">True</property><property name=\"mnemonic_widget\">snap_width_s"
  "cale</property></object><packing><property name=\"position\">0</propert"
  "y></packing></child><child><object class=\"GtkAlignment\" id=\"alignmen"
  "t6\"><property name=\"visible\">True</property><property name=\"left_pa"
  "dding\">12</property><child><object class=\"GtkHBox\" id=\"hbox1\"><pro"
  "perty name=\"visible\">True</property><property name=\"spacing\">12</pr"
  "operty><child><object class=\"GtkLabel\" id=\"label11\"><property name="
  "\"visible\">True</property><property name=\"label\" translatable=\"yes\""
  " comments=\"Snapping distance\">&lt;i&gt;Small&lt;/i&gt;</property><pro"
  "perty name=\"use_markup\">True</property></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">False</property><"
  "property name=\"position\">0</property></packing></child><child><object"
  " class=\"GtkHScale\" id=\"snap_width_scale\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"update_policy\">discontinuous</property><property name=\"adjustme"
  "nt\">adjustment3</property><property name=\"restrict_to_fill_level\">Fa"
  "lse</property><property name=\"draw_value\">False</property></object><p"
  "acking><property name=\"position\">1</property></packing></child><child"
  "><object class=\"GtkLabel\" id=\"label12\"><property name=\"visible\">T"
  "rue</property><property name=\"label\" translatable=\"yes\" comments=\""
  "Snapping distance\">&lt;i&gt;Wide&lt;/i&gt;</property><property name=\""
  "use_markup\">True</property></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">False</property><property name"
  "=\"position\">2</property></packing></child></object></child></object><"
  "packing><property name=\"position\">1</property></packing></child></obj"
  "ect><packing><property name=\"position\">2</property></packing></child>"
  "</object></child></object></child><child type=\"label\"><object class=\""
  "GtkLabel\" id=\"label5\"><property name=\"visible\">True</property><pro"
  "perty name=\"label\" translatable=\"yes\">&lt;b&gt;Windows snapping&lt;"
  "/b&gt;</property><property name=\"use_markup\">True</property></object>"
  "</child></object><packing><property name=\"expand\">False</property><pr"
  "operty name=\"position\">0</property></packing></child><child><object c"
  "lass=\"GtkFrame\" id=\"frame2\"><property name=\"visible\">True</proper"
  "ty><property name=\"label_xalign\">0</property><property name=\"shadow_"
  "type\">none</property><child><object class=\"GtkAlignment\" id=\"alignm"
  "ent3\"><property name=\"visible\">True</property><property name=\"borde"
  "r_width\">6</property><property name=\"bottom_padding\">6</property><pr"
  "operty name=\"left_padding\">12</property><child><object class=\"GtkVBo"
  "x\" id=\"vbox4\"><property name=\"visible\">True</property><property na"
  "me=\"orientation\">vertical</property><property name=\"spacing\">6</pro"
  "perty><child><object class=\"GtkCheckButton\" id=\"wrap_workspaces_chec"
  "k\"><property name=\"label\" translatable=\"yes\">Wrap workspaces when "
  "the _pointer reaches the screen edge</property><property name=\"visible"
  "\">True</property><property name=\"can_focus\">True</property><property"
  " name=\"receives_default\">False</property><property name=\"use_underli"
  "ne\">True</property><property name=\"draw_indicator\">True</property></"
  "object><packing><property name=\"position\">0</property></packing></chi"
  "ld><child><object class=\"GtkCheckButton\" id=\"wrap_windows_check\"><p"
  "roperty name=\"label\" translatable=\"yes\">Wrap workspaces when _dragg"
  "ing a window off the screen</property><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"r"
  "eceives_default\">False</property><property name=\"use_underline\">True"
  "</property><property name=\"draw_indicator\">True</property></object><p"
  "acking><property name=\"position\">1</property></packing></child><child"
  "><object class=\"GtkVBox\" id=\"vbox6\"><property name=\"visible\">True"
  "</property><property name=\"orientation\">vertical</property><property "
  "name=\"spacing\">6</property><child><object class=\"GtkLabel\" id=\"lab"
  "el10\"><property name=\"visible\">True</property><property name=\"xalig"
  "n\">0</property><property name=\"label\" translatable=\"yes\">_Edge res"
  "istance:</property><property name=\"use_underline\">True</property><pro"
  "perty name=\"selectable\">True</property><property name=\"mnemonic_widg"
  "et\">wrap_resistance_scale</property></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">False</property><prope"
  "rty name=\"position\">0</property></packing></child><child><object clas"
  "s=\"GtkAlignment\" id=\"alignment4\"><property name=\"visible\">True</p"
  "roperty><property name=\"left_padding\">12</property><child><object cla"
  "ss=\"GtkHBox\" id=\"hbox2\"><property name=\"visible\">True</property><"
  "property name=\"spacing\">12</property><child><object class=\"GtkLabel\""
  " id=\"label13\"><property name=\"visible\">True</property><property nam"
  "e=\"label\" translatable=\"yes\" comments=\"Edge resistance\">&lt;i&gt;"
  "Small&lt;/i&gt;</property><property name=\"use_markup\">True</property>"
  "</object><packing><property name=\"expand\">False</property><property n"
  "ame=\"fill\">False</property><property name=\"position\">0</property></"
  "packing></child><child><object class=\"GtkHScale\" id=\"wrap_resistance"
  "_scale\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">True</property><property name=\"update_policy\">discontinuous<"
  "/property><property name=\"adjustment\">adjustment4</property><property"
  " name=\"restrict_to_fill_level\">False</property><property name=\"draw_"
  "value\">False</property></object><packing><property name=\"position\">1"
  "</property></packing></child><child><object class=\"GtkLabel\" id=\"lab"
  "el14\"><property name=\"visible\">True</property><property name=\"label"
  "\" translatable=\"yes\" comments=\"Edge resistance\">&lt;i&gt;Wide&lt;/"
  "i&gt;</property><property name=\"use_markup\">True</property></object><"
  "packing><property name=\"expand\">False</property><property name=\"fill"
  "\">False</property><property name=\"position\">2</property></packing></"
  "child></object></child></object><packing><property name=\"position\">1<"
  "/property></packing></child></object><packing><property name=\"position"
  "\">2</property></packing></child></object></child></object></child><chi"
  "ld type=\"label\"><object class=\"GtkLabel\" id=\"label6\"><property na"
  "me=\"visible\">True</property><property name=\"label\" translatable=\"y"
  "es\">&lt;b&gt;Wrap workspaces&lt;/b&gt;</property><property name=\"use_"
  "markup\">True</property></object></child></object><packing><property na"
  "me=\"expand\">False</property><property name=\"position\">1</property><"
  "/packing></child><child><object class=\"GtkFrame\" id=\"frame3\"><prope"
  "rty name=\"visible\">True</property><property name=\"label_xalign\">0</"
  "property><property name=\"shadow_type\">none</property><child><object c"
  "lass=\"GtkAlignment\" id=\"alignment5\"><property name=\"visible\">True"
  "</property><property name=\"border_width\">6</property><property name=\""
  "bottom_padding\">6</property><property name=\"left_padding\">12</proper"
  "ty><child><object class=\"GtkVBox\" id=\"vbox3\"><property name=\"visib"
  "le\">True</property><property name=\"orientation\">vertical</property><"
  "property name=\"spacing\">6</property><child><object class=\"GtkCheckBu"
  "tton\" id=\"box_resize_check\"><property name=\"label\" translatable=\""
  "yes\">Hide content of windows when _resizing</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"receives_default\">False</property><property name=\"use_"
  "underline\">True</property><property name=\"draw_indicator\">True</prop"
  "erty></object><packing><property name=\"expand\">False</property><prope"
  "rty name=\"fill\">False</property><property name=\"position\">0</proper"
  "ty></packing></child><child><object class=\"GtkCheckButton\" id=\"box_m"
  "ove_check\"><property name=\"label\" translatable=\"yes\">Hide content "
  "of windows when _moving</property><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">True</property><property name=\"recei"
  "ves_default\">False</property><property name=\"use_underline\">True</pr"
  "operty><property name=\"draw_indicator\">True</property></object><packi"
  "ng><property name=\"expand\">False</property><property name=\"fill\">Fa"
  "lse</property><property name=\"position\">1</property></packing></child"
  "></object></child></object></child><child type=\"label\"><object class="
  "\"GtkLabel\" id=\"label7\"><property name=\"visible\">True</property><p"
  "roperty name=\"label\" translatable=\"yes\">&lt;b&gt;Box move and resiz"
  "e&lt;/b&gt;</property><property name=\"use_markup\">True</property></ob"
  "ject></child></object><packing><property name=\"expand\">False</propert"
  "y><property name=\"position\">2</property></packing></child><child><obj"
  "ect class=\"GtkFrame\" id=\"frame4\"><property name=\"visible\">True</p"
  "roperty><property name=\"label_xalign\">0</property><property name=\"sh"
  "adow_type\">none</property><child><object class=\"GtkAlignment\" id=\"a"
  "lignment13\"><property name=\"visible\">True</property><property name=\""
  "top_padding\">6</property><property name=\"bottom_padding\">6</property"
  "><property name=\"left_padding\">18</property><child><object class=\"Gt"
  "kComboBox\" id=\"double_click_action_combo\"><property name=\"visible\""
  ">True</property><property name=\"tooltip_text\" translatable=\"yes\">Th"
  "e action to perform when the title-bar is double-clicked</property></ob"
  "ject></child></object></child><child type=\"label\"><object class=\"Gtk"
  "Label\" id=\"label8\"><property name=\"visible\">True</property><proper"
  "ty name=\"label\" translatable=\"yes\">&lt;b&gt;Double click _action&lt"
  ";/b&gt;</property><property name=\"use_markup\">True</property><propert"
  "y name=\"use_underline\">True</property><property name=\"mnemonic_widge"
  "t\">double_click_action_combo</property></object></child></object><pack"
  "ing><property name=\"expand\">False</property><property name=\"position"
  "\">3</property></packing></child></object><packing><property name=\"pos"
  "ition\">3</property></packing></child><child type=\"tab\"><object class"
  "=\"GtkLabel\" id=\"label4\"><property name=\"visible\">True</property><"
  "property name=\"label\" translatable=\"yes\">Ad_vanced</property><prope"
  "rty name=\"use_underline\">True</property></object><packing><property n"
  "ame=\"position\">3</property><property name=\"tab_fill\">False</propert"
  "y></packing></child></object><packing><property name=\"position\">1</pr"
  "operty></packing></child><child internal-child=\"action_area\"><object "
  "class=\"GtkHButtonBox\" id=\"dialog-action_area1\"><property name=\"vis"
  "ible\">True</property><property name=\"layout_style\">end</property><ch"
  "ild><object class=\"GtkButton\" id=\"help_button\"><property name=\"lab"
  "el\">gtk-help</property><property name=\"visible\">True</property><prop"
  "erty name=\"sensitive\">False</property><property name=\"can_focus\">Tr"
  "ue</property><property name=\"receives_default\">True</property><proper"
  "ty name=\"use_stock\">True</property></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">False</property><prope"
  "rty name=\"position\">0</property><property name=\"secondary\">True</pr"
  "operty></packing></child><child><object class=\"GtkButton\" id=\"close_"
  "button\"><property name=\"label\">gtk-close</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"receives_default\">True</property><property name=\"use_s"
  "tock\">True</property></object><packing><property name=\"expand\">False"
  "</property><property name=\"fill\">False</property><property name=\"pos"
  "ition\">1</property></packing></child></object><packing><property name="
  "\"expand\">False</property><property name=\"pack_type\">end</property><"
  "property name=\"position\">0</property></packing></child></object></chi"
  "ld><action-widgets><action-widget response=\"0\">help_button</action-wi"
  "dget><action-widget response=\"0\">close_button</action-widget></action"
  "-widgets></object></interface>"
};

static const unsigned xfwm4_dialog_ui_length = 39818u;

