/* automatically generated from xfwm4-tweaks-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (tweaks_dialog_ui)
#endif
#ifdef __GNUC__
static const char tweaks_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char tweaks_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\"?><interface><object class=\"GtkAdjustment\" id=\""
  "adjustment1\"><property name=\"value\">75</property><property name=\"up"
  "per\">100</property><property name=\"step_increment\">1</property><prop"
  "erty name=\"page_increment\">10</property></object><object class=\"GtkA"
  "djustment\" id=\"adjustment2\"><property name=\"value\">90</property><p"
  "roperty name=\"upper\">100</property><property name=\"step_increment\">"
  "1</property><property name=\"page_increment\">10</property></object><ob"
  "ject class=\"GtkAdjustment\" id=\"adjustment3\"><property name=\"value\""
  ">90</property><property name=\"upper\">100</property><property name=\"s"
  "tep_increment\">1</property><property name=\"page_increment\">10</prope"
  "rty></object><object class=\"GtkAdjustment\" id=\"adjustment4\"><proper"
  "ty name=\"value\">90</property><property name=\"upper\">100</property><"
  "property name=\"step_increment\">1</property><property name=\"page_incr"
  "ement\">10</property></object><object class=\"GtkAdjustment\" id=\"adju"
  "stment5\"><property name=\"value\">90</property><property name=\"upper\""
  ">100</property><property name=\"step_increment\">1</property><property "
  "name=\"page_increment\">10</property></object><object class=\"GtkAdjust"
  "ment\" id=\"adjustment6\"><property name=\"value\">90</property><proper"
  "ty name=\"upper\">100</property><property name=\"step_increment\">1</pr"
  "operty><property name=\"page_increment\">10</property></object><object "
  "class=\"XfceTitledDialog\" id=\"main-dialog\"><property name=\"title\" "
  "translatable=\"yes\">Window Manager Tweaks</property><property name=\"w"
  "indow_position\">center-on-parent</property><property name=\"default_he"
  "ight\">480</property><property name=\"icon_name\">wmtweaks</property><p"
  "roperty name=\"type_hint\">dialog</property><property name=\"has_separa"
  "tor\">False</property><property name=\"subtitle\" translatable=\"yes\">"
  "Fine-tune window behaviour and effects</property><child internal-child="
  "\"vbox\"><object class=\"GtkVBox\" id=\"main-vbox\"><property name=\"vi"
  "sible\">True</property><property name=\"orientation\">vertical</propert"
  "y><child><object class=\"GtkNotebook\" id=\"plug-child\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">True</property"
  "><property name=\"border_width\">6</property><child><object class=\"Gtk"
  "VBox\" id=\"vbox1\"><property name=\"visible\">True</property><property"
  " name=\"border_width\">12</property><property name=\"orientation\">vert"
  "ical</property><property name=\"spacing\">6</property><child><object cl"
  "ass=\"GtkCheckButton\" id=\"cycle_minimum_check\"><property name=\"labe"
  "l\" translatable=\"yes\">_Skip windows that have \"skip pager\"\nor \"s"
  "kip taskbar\" properties set</property><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">True</property><property name=\""
  "receives_default\">False</property><property name=\"use_underline\">Tru"
  "e</property><property name=\"draw_indicator\">True</property></object><"
  "packing><property name=\"expand\">False</property><property name=\"fill"
  "\">False</property><property name=\"position\">0</property></packing></"
  "child><child><object class=\"GtkCheckButton\" id=\"cycle_hidden_check\""
  "><property name=\"label\" translatable=\"yes\">_Include hidden (i.e. ic"
  "onified) windows</property><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">True</property><property name=\"receives_def"
  "ault\">False</property><property name=\"use_underline\">True</property>"
  "<property name=\"draw_indicator\">True</property></object><packing><pro"
  "perty name=\"expand\">False</property><property name=\"fill\">False</pr"
  "operty><property name=\"position\">1</property></packing></child><child"
  "><object class=\"GtkCheckButton\" id=\"cycle_workspaces_check\"><proper"
  "ty name=\"label\" translatable=\"yes\">Cycle _through windows on all wo"
  "rkspaces</property><property name=\"visible\">True</property><property "
  "name=\"can_focus\">True</property><property name=\"receives_default\">F"
  "alse</property><property name=\"use_underline\">True</property><propert"
  "y name=\"draw_indicator\">True</property></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">False</property><"
  "property name=\"position\">2</property></packing></child><child><object"
  " class=\"GtkCheckButton\" id=\"cycle_draw_frame\"><property name=\"labe"
  "l\" translatable=\"yes\">_Draw frame around selected windows while cycl"
  "ing</property><property name=\"visible\">True</property><property name="
  "\"can_focus\">True</property><property name=\"receives_default\">False<"
  "/property><property name=\"use_underline\">True</property><property nam"
  "e=\"draw_indicator\">True</property></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">False</property><prope"
  "rty name=\"position\">3</property></packing></child></object></child><c"
  "hild type=\"tab\"><object class=\"GtkLabel\" id=\"label1\"><property na"
  "me=\"visible\">True</property><property name=\"label\" translatable=\"y"
  "es\">C_ycling</property><property name=\"use_underline\">True</property"
  "></object><packing><property name=\"tab_fill\">False</property></packin"
  "g></child><child><object class=\"GtkVBox\" id=\"vbox3\"><property name="
  "\"visible\">True</property><property name=\"border_width\">12</property"
  "><property name=\"orientation\">vertical</property><property name=\"spa"
  "cing\">6</property><child><object class=\"GtkCheckButton\" id=\"prevent"
  "_focus_stealing_check\"><property name=\"label\" translatable=\"yes\">A"
  "ctivate _focus stealing prevention</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"receives_default\">False</property><property name=\"use_underline"
  "\">True</property><property name=\"draw_indicator\">True</property></ob"
  "ject><packing><property name=\"expand\">False</property><property name="
  "\"fill\">False</property><property name=\"position\">0</property></pack"
  "ing></child><child><object class=\"GtkCheckButton\" id=\"focus_hint_che"
  "ck\"><property name=\"label\" translatable=\"yes\">Honor _standard ICCC"
  "M focus hint</property><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">True</property><property name=\"receives_default"
  "\">False</property><property name=\"use_underline\">True</property><pro"
  "perty name=\"draw_indicator\">True</property></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"fill\">False</proper"
  "ty><property name=\"position\">1</property></packing></child><child><ob"
  "ject class=\"GtkVBox\" id=\"prevent_focus_stealing_box\"><property name"
  "=\"visible\">True</property><property name=\"orientation\">vertical</pr"
  "operty><property name=\"spacing\">6</property><child><object class=\"Gt"
  "kLabel\" id=\"label11\"><property name=\"visible\">True</property><prop"
  "erty name=\"xalign\">0</property><property name=\"label\" translatable="
  "\"yes\">When a window raises itself:</property></object><packing><prope"
  "rty name=\"position\">0</property></packing></child><child><object clas"
  "s=\"GtkAlignment\" id=\"alignment2\"><property name=\"visible\">True</p"
  "roperty><property name=\"bottom_padding\">6</property><property name=\""
  "left_padding\">12</property><child><object class=\"GtkVBox\" id=\"vbox1"
  "4\"><property name=\"visible\">True</property><property name=\"border_w"
  "idth\">6</property><property name=\"orientation\">vertical</property><p"
  "roperty name=\"spacing\">6</property><child><object class=\"GtkRadioBut"
  "ton\" id=\"activate_action_bring_option\"><property name=\"label\" tran"
  "slatable=\"yes\">_Bring window on current workspace</property><property"
  " name=\"visible\">True</property><property name=\"can_focus\">True</pro"
  "perty><property name=\"receives_default\">False</property><property nam"
  "e=\"use_underline\">True</property><property name=\"active\">True</prop"
  "erty><property name=\"draw_indicator\">True</property></object><packing"
  "><property name=\"position\">0</property></packing></child><child><obje"
  "ct class=\"GtkRadioButton\" id=\"activate_action_switch_option\"><prope"
  "rty name=\"label\" translatable=\"yes\">Switch to win_dow\'s workspace<"
  "/property><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">True</property><property name=\"receives_default\">False</pro"
  "perty><property name=\"use_underline\">True</property><property name=\""
  "active\">True</property><property name=\"draw_indicator\">True</propert"
  "y><property name=\"group\">activate_action_bring_option</property></obj"
  "ect><packing><property name=\"position\">1</property></packing></child>"
  "<child><object class=\"GtkRadioButton\" id=\"activate_action_none_optio"
  "n\"><property name=\"label\" translatable=\"yes\">Do _nothing</property"
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"receives_default\">False</property><pr"
  "operty name=\"use_underline\">True</property><property name=\"active\">"
  "True</property><property name=\"draw_indicator\">True</property><proper"
  "ty name=\"group\">activate_action_bring_option</property></object><pack"
  "ing><property name=\"position\">2</property></packing></child></object>"
  "</child></object><packing><property name=\"position\">1</property></pac"
  "king></child></object><packing><property name=\"expand\">False</propert"
  "y><property name=\"fill\">False</property><property name=\"position\">2"
  "</property></packing></child></object><packing><property name=\"positio"
  "n\">1</property></packing></child><child type=\"tab\"><object class=\"G"
  "tkLabel\" id=\"label2\"><property name=\"visible\">True</property><prop"
  "erty name=\"label\" translatable=\"yes\">_Focus</property><property nam"
  "e=\"use_underline\">True</property></object><packing><property name=\"p"
  "osition\">1</property><property name=\"tab_fill\">False</property></pac"
  "king></child><child><object class=\"GtkVBox\" id=\"vbox4\"><property na"
  "me=\"visible\">True</property><property name=\"border_width\">12</prope"
  "rty><property name=\"orientation\">vertical</property><property name=\""
  "spacing\">6</property><child><object class=\"GtkHBox\" id=\"hbox1\"><pr"
  "operty name=\"visible\">True</property><property name=\"spacing\">12</p"
  "roperty><child><object class=\"GtkLabel\" id=\"label7\"><property name="
  "\"visible\">True</property><property name=\"xalign\">0</property><prope"
  "rty name=\"label\" translatable=\"yes\">Key used to _grab and move wind"
  "ows:</property><property name=\"use_underline\">True</property><propert"
  "y name=\"mnemonic_widget\">easy_click_combo_box</property></object><pac"
  "king><property name=\"expand\">False</property><property name=\"fill\">"
  "False</property><property name=\"position\">0</property></packing></chi"
  "ld><child><object class=\"GtkComboBox\" id=\"easy_click_combo_box\"><pr"
  "operty name=\"visible\">True</property></object><packing><property name"
  "=\"expand\">False</property><property name=\"fill\">False</property><pr"
  "operty name=\"position\">1</property></packing></child></object><packin"
  "g><property name=\"expand\">False</property><property name=\"fill\">Fal"
  "se</property><property name=\"position\">0</property></packing></child>"
  "<child><object class=\"GtkCheckButton\" id=\"raise_with_any_button_chec"
  "k\"><property name=\"label\" translatable=\"yes\">_Raise windows when a"
  "ny mouse button is pressed</property><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">True</property><property name=\"re"
  "ceives_default\">False</property><property name=\"use_underline\">True<"
  "/property><property name=\"draw_indicator\">True</property></object><pa"
  "cking><property name=\"expand\">False</property><property name=\"fill\""
  ">False</property><property name=\"position\">1</property></packing></ch"
  "ild><child><object class=\"GtkCheckButton\" id=\"borderless_maximize_ch"
  "eck\"><property name=\"label\" translatable=\"yes\">Hide _frame of wind"
  "ows when maximized</property><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">True</property><property name=\"receives_d"
  "efault\">False</property><property name=\"use_underline\">True</propert"
  "y><property name=\"draw_indicator\">True</property></object><packing><p"
  "roperty name=\"expand\">False</property><property name=\"fill\">False</"
  "property><property name=\"position\">2</property></packing></child><chi"
  "ld><object class=\"GtkCheckButton\" id=\"restore_on_move_check\"><prope"
  "rty name=\"label\" translatable=\"yes\">Restore original _size of maxim"
  "ized windows when moving</property><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">True</property><property name=\"rece"
  "ives_default\">False</property><property name=\"use_underline\">True</p"
  "roperty><property name=\"draw_indicator\">True</property></object><pack"
  "ing><property name=\"expand\">False</property><property name=\"fill\">F"
  "alse</property><property name=\"position\">3</property></packing></chil"
  "d><child><object class=\"GtkCheckButton\" id=\"snap_resist_check\"><pro"
  "perty name=\"label\" translatable=\"yes\">Use _edge resistance instead "
  "of window snapping</property><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">True</property><property name=\"receives_d"
  "efault\">False</property><property name=\"use_underline\">True</propert"
  "y><property name=\"draw_indicator\">True</property></object><packing><p"
  "roperty name=\"expand\">False</property><property name=\"fill\">False</"
  "property><property name=\"position\">4</property></packing></child><chi"
  "ld><object class=\"GtkCheckButton\" id=\"urgent_blink\"><property name="
  "\"label\" translatable=\"yes\">Notify of _urgency by making window\'s d"
  "ecoration blink</property><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">True</property><property name=\"receives_defa"
  "ult\">False</property><property name=\"use_underline\">True</property><"
  "property name=\"draw_indicator\">True</property></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">False</pro"
  "perty><property name=\"position\">5</property></packing></child><child>"
  "<object class=\"GtkCheckButton\" id=\"repeat_urgent_blink\"><property n"
  "ame=\"label\" translatable=\"yes\">Keep urgent windows _blinking repeat"
  "edly</property><property name=\"visible\">True</property><property name"
  "=\"can_focus\">True</property><property name=\"receives_default\">False"
  "</property><property name=\"use_underline\">True</property><property na"
  "me=\"draw_indicator\">True</property></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">False</property><prope"
  "rty name=\"position\">6</property></packing></child></object><packing><"
  "property name=\"position\">2</property></packing></child><child type=\""
  "tab\"><object class=\"GtkLabel\" id=\"label3\"><property name=\"visible"
  "\">True</property><property name=\"label\" translatable=\"yes\">_Access"
  "ibility</property><property name=\"use_underline\">True</property></obj"
  "ect><packing><property name=\"position\">2</property><property name=\"t"
  "ab_fill\">False</property></packing></child><child><object class=\"GtkV"
  "Box\" id=\"vbox5\"><property name=\"visible\">True</property><property "
  "name=\"border_width\">12</property><property name=\"orientation\">verti"
  "cal</property><property name=\"spacing\">6</property><child><object cla"
  "ss=\"GtkCheckButton\" id=\"scroll_workspaces_check\"><property name=\"l"
  "abel\" translatable=\"yes\">Use the _mouse wheel on the desktop to swit"
  "ch workspaces</property><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">True</property><property name=\"receives_defaul"
  "t\">False</property><property name=\"use_underline\">True</property><pr"
  "operty name=\"draw_indicator\">True</property></object><packing><proper"
  "ty name=\"expand\">False</property><property name=\"fill\">False</prope"
  "rty><property name=\"position\">0</property></packing></child><child><o"
  "bject class=\"GtkCheckButton\" id=\"toggle_workspaces_check\"><property"
  " name=\"label\" translatable=\"yes\">_Remember and recall previous work"
  "space\nwhen switching via keyboard shortcuts</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"receives_default\">False</property><property name=\"use_"
  "underline\">True</property><property name=\"draw_indicator\">True</prop"
  "erty></object><packing><property name=\"expand\">False</property><prope"
  "rty name=\"fill\">False</property><property name=\"position\">1</proper"
  "ty></packing></child><child><object class=\"GtkCheckButton\" id=\"wrap_"
  "layout_check\"><property name=\"label\" translatable=\"yes\">Wrap works"
  "paces depending on the actual desktop _layout</property><property name="
  "\"visible\">True</property><property name=\"can_focus\">True</property>"
  "<property name=\"receives_default\">False</property><property name=\"us"
  "e_underline\">True</property><property name=\"draw_indicator\">True</pr"
  "operty></object><packing><property name=\"expand\">False</property><pro"
  "perty name=\"fill\">False</property><property name=\"position\">2</prop"
  "erty></packing></child><child><object class=\"GtkCheckButton\" id=\"wra"
  "p_cycle_check\"><property name=\"label\" translatable=\"yes\">Wrap work"
  "spaces when the _first or the last workspace is reached</property><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">True<"
  "/property><property name=\"receives_default\">False</property><property"
  " name=\"use_underline\">True</property><property name=\"draw_indicator\""
  ">True</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">False</property><property name=\"position\""
  ">3</property></packing></child></object><packing><property name=\"posit"
  "ion\">3</property></packing></child><child type=\"tab\"><object class=\""
  "GtkLabel\" id=\"label4\"><property name=\"visible\">True</property><pro"
  "perty name=\"label\" translatable=\"yes\">_Workspaces</property><proper"
  "ty name=\"use_underline\">True</property></object><packing><property na"
  "me=\"position\">3</property><property name=\"tab_fill\">False</property"
  "></packing></child><child><object class=\"GtkVBox\" id=\"vbox6\"><prope"
  "rty name=\"visible\">True</property><property name=\"border_width\">12<"
  "/property><property name=\"orientation\">vertical</property><property n"
  "ame=\"spacing\">6</property><child><object class=\"GtkLabel\" id=\"labe"
  "l8\"><property name=\"visible\">True</property><property name=\"xalign\""
  ">0</property><property name=\"label\" translatable=\"yes\">_Minimum siz"
  "e of windows to trigger smart placement:</property><property name=\"use"
  "_underline\">True</property><property name=\"mnemonic_widget\">placemen"
  "t_ratio_scale</property></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">False</property><property name=\"p"
  "osition\">0</property></packing></child><child><object class=\"GtkAlign"
  "ment\" id=\"alignment4\"><property name=\"visible\">True</property><pro"
  "perty name=\"bottom_padding\">6</property><property name=\"left_padding"
  "\">12</property><child><object class=\"GtkHBox\" id=\"hbox2\"><property"
  " name=\"visible\">True</property><child><object class=\"GtkLabel\" id=\""
  "label9\"><property name=\"visible\">True</property><property name=\"lab"
  "el\" translatable=\"yes\" comments=\"Smart placement size\">&lt;i&gt;Sm"
  "all&lt;/i&gt;</property><property name=\"use_markup\">True</property></"
  "object><packing><property name=\"expand\">False</property><property nam"
  "e=\"fill\">False</property><property name=\"position\">0</property></pa"
  "cking></child><child><object class=\"GtkHScale\" id=\"placement_ratio_s"
  "cale\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">True</property><property name=\"adjustment\">adjustment1</proper"
  "ty><property name=\"restrict_to_fill_level\">False</property><property "
  "name=\"draw_value\">False</property></object><packing><property name=\""
  "position\">1</property></packing></child><child><object class=\"GtkLabe"
  "l\" id=\"label10\"><property name=\"visible\">True</property><property "
  "name=\"label\" translatable=\"yes\" comments=\"Smart placement size\">&"
  "lt;i&gt;Large&lt;/i&gt;</property><property name=\"use_markup\">True</p"
  "roperty></object><packing><property name=\"expand\">False</property><pr"
  "operty name=\"position\">2</property></packing></child></object></child"
  "></object><packing><property name=\"expand\">False</property><property "
  "name=\"fill\">False</property><property name=\"position\">1</property><"
  "/packing></child><child><object class=\"GtkVBox\" id=\"default_placemen"
  "t_box\"><property name=\"visible\">True</property><property name=\"orie"
  "ntation\">vertical</property><property name=\"spacing\">6</property><ch"
  "ild><object class=\"GtkLabel\" id=\"label27\"><property name=\"visible\""
  ">True</property><property name=\"xalign\">0</property><property name=\""
  "label\" translatable=\"yes\">By default, place windows:</property></obj"
  "ect><packing><property name=\"position\">0</property></packing></child>"
  "<child><object class=\"GtkAlignment\" id=\"alignment10\"><property name"
  "=\"visible\">True</property><property name=\"bottom_padding\">6</proper"
  "ty><property name=\"left_padding\">12</property><child><object class=\""
  "GtkVBox\" id=\"vbox18\"><property name=\"visible\">True</property><prop"
  "erty name=\"border_width\">6</property><property name=\"orientation\">v"
  "ertical</property><property name=\"spacing\">6</property><child><object"
  " class=\"GtkRadioButton\" id=\"placement_center_option\"><property name"
  "=\"label\" translatable=\"yes\">At the _center of the screen</property>"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "True</property><property name=\"receives_default\">False</property><pro"
  "perty name=\"use_underline\">True</property><property name=\"draw_indic"
  "ator\">True</property></object><packing><property name=\"position\">0</"
  "property></packing></child><child><object class=\"GtkRadioButton\" id=\""
  "placement_mouse_option\"><property name=\"label\" translatable=\"yes\">"
  "Under the mouse _pointer</property><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">True</property><property name=\"rece"
  "ives_default\">False</property><property name=\"use_underline\">True</p"
  "roperty><property name=\"active\">True</property><property name=\"draw_"
  "indicator\">True</property><property name=\"group\">placement_center_op"
  "tion</property></object><packing><property name=\"position\">1</propert"
  "y></packing></child></object></child></object><packing><property name=\""
  "position\">1</property></packing></child></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">False</property><"
  "property name=\"position\">2</property></packing></child></object><pack"
  "ing><property name=\"position\">4</property></packing></child><child ty"
  "pe=\"tab\"><object class=\"GtkLabel\" id=\"label5\"><property name=\"vi"
  "sible\">True</property><property name=\"label\" translatable=\"yes\">_P"
  "lacement</property><property name=\"use_underline\">True</property></ob"
  "ject><packing><property name=\"position\">4</property><property name=\""
  "tab_fill\">False</property></packing></child><child><object class=\"Gtk"
  "VBox\" id=\"vbox7\"><property name=\"visible\">True</property><property"
  " name=\"border_width\">12</property><property name=\"orientation\">vert"
  "ical</property><property name=\"spacing\">6</property><child><object cl"
  "ass=\"GtkCheckButton\" id=\"use_compositing_check\"><property name=\"la"
  "bel\" translatable=\"yes\">_Enable display compositing</property><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">True</"
  "property><property name=\"receives_default\">False</property><property "
  "name=\"use_underline\">True</property><property name=\"draw_indicator\""
  ">True</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">False</property><property name=\"position\""
  ">0</property></packing></child><child><object class=\"GtkScrolledWindow"
  "\" id=\"use_compositing_box\"><property name=\"visible\">True</property"
  "><property name=\"sensitive\">False</property><property name=\"can_focu"
  "s\">True</property><property name=\"hscrollbar_policy\">never</property"
  "><property name=\"vscrollbar_policy\">automatic</property><child><objec"
  "t class=\"GtkViewport\" id=\"viewport1\"><property name=\"visible\">Tru"
  "e</property><property name=\"resize_mode\">queue</property><property na"
  "me=\"shadow_type\">none</property><child><object class=\"GtkAlignment\""
  " id=\"alignment3\"><property name=\"visible\">True</property><property "
  "name=\"bottom_padding\">6</property><property name=\"left_padding\">12<"
  "/property><child><object class=\"GtkVBox\" id=\"vbox8\"><property name="
  "\"visible\">True</property><property name=\"orientation\">vertical</pro"
  "perty><property name=\"spacing\">6</property><child><object class=\"Gtk"
  "CheckButton\" id=\"unredirect_overlays_check\"><property name=\"label\""
  " translatable=\"yes\">Display _fullscreen overlay windows directly</pro"
  "perty><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">True</property><property name=\"receives_default\">False</propert"
  "y><property name=\"use_underline\">True</property><property name=\"draw"
  "_indicator\">True</property></object><packing><property name=\"expand\""
  ">False</property><property name=\"position\">0</property></packing></ch"
  "ild><child><object class=\"GtkCheckButton\" id=\"show_frame_shadow_chec"
  "k\"><property name=\"label\" translatable=\"yes\">Show shadows under _r"
  "egular windows</property><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">True</property><property name=\"receives_defau"
  "lt\">False</property><property name=\"use_underline\">True</property><p"
  "roperty name=\"draw_indicator\">True</property></object><packing><prope"
  "rty name=\"expand\">False</property><property name=\"position\">1</prop"
  "erty></packing></child><child><object class=\"GtkCheckButton\" id=\"sho"
  "w_popup_shadow_check\"><property name=\"label\" translatable=\"yes\">Sh"
  "ow shadows under pop_up windows</property><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">True</property><property name"
  "=\"receives_default\">False</property><property name=\"use_underline\">"
  "True</property><property name=\"draw_indicator\">True</property></objec"
  "t><packing><property name=\"expand\">False</property><property name=\"p"
  "osition\">2</property></packing></child><child><object class=\"GtkCheck"
  "Button\" id=\"show_dock_shadow_check\"><property name=\"label\" transla"
  "table=\"yes\">Show shadows under _dock windows</property><property name"
  "=\"visible\">True</property><property name=\"can_focus\">True</property"
  "><property name=\"receives_default\">False</property><property name=\"u"
  "se_underline\">True</property><property name=\"draw_indicator\">True</p"
  "roperty></object><packing><property name=\"expand\">False</property><pr"
  "operty name=\"position\">3</property></packing></child><child><object c"
  "lass=\"GtkLabel\" id=\"label12\"><property name=\"visible\">True</prope"
  "rty><property name=\"xalign\">0</property><property name=\"label\" tran"
  "slatable=\"yes\">Opaci_ty of window decorations:</property><property na"
  "me=\"use_underline\">True</property><property name=\"mnemonic_widget\">"
  "frame_opacity_scale</property></object><packing><property name=\"expand"
  "\">False</property><property name=\"position\">4</property></packing></"
  "child><child><object class=\"GtkAlignment\" id=\"alignment5\"><property"
  " name=\"visible\">True</property><property name=\"top_padding\">2</prop"
  "erty><property name=\"left_padding\">12</property><child><object class="
  "\"GtkHBox\" id=\"hbox3\"><property name=\"visible\">True</property><chi"
  "ld><object class=\"GtkLabel\" id=\"label17\"><property name=\"visible\""
  ">True</property><property name=\"label\" translatable=\"yes\">&lt;i&gt;"
  "Transparent&lt;/i&gt;</property><property name=\"use_markup\">True</pro"
  "perty></object><packing><property name=\"expand\">False</property><prop"
  "erty name=\"fill\">False</property><property name=\"position\">0</prope"
  "rty></packing></child><child><object class=\"GtkHScale\" id=\"frame_opa"
  "city_scale\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"update_policy\">discontinuo"
  "us</property><property name=\"adjustment\">adjustment2</property><prope"
  "rty name=\"restrict_to_fill_level\">False</property><property name=\"dr"
  "aw_value\">False</property></object><packing><property name=\"position\""
  ">1</property></packing></child><child><object class=\"GtkLabel\" id=\"l"
  "abel18\"><property name=\"visible\">True</property><property name=\"lab"
  "el\" translatable=\"yes\">&lt;i&gt;Opaque&lt;/i&gt;</property><property"
  " name=\"use_markup\">True</property></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">False</property><prope"
  "rty name=\"position\">2</property></packing></child></object></child></"
  "object><packing><property name=\"expand\">False</property><property nam"
  "e=\"fill\">False</property><property name=\"position\">5</property></pa"
  "cking></child><child><object class=\"GtkLabel\" id=\"label13\"><propert"
  "y name=\"visible\">True</property><property name=\"xalign\">0</property"
  "><property name=\"label\" translatable=\"yes\">Opacity of _inactive win"
  "dows:</property><property name=\"use_underline\">True</property><proper"
  "ty name=\"mnemonic_widget\">inactive_opacity_scale</property></object><"
  "packing><property name=\"expand\">False</property><property name=\"fill"
  "\">False</property><property name=\"position\">6</property></packing></"
  "child><child><object class=\"GtkAlignment\" id=\"alignment6\"><property"
  " name=\"visible\">True</property><property name=\"top_padding\">2</prop"
  "erty><property name=\"left_padding\">12</property><child><object class="
  "\"GtkHBox\" id=\"hbox4\"><property name=\"visible\">True</property><chi"
  "ld><object class=\"GtkLabel\" id=\"label19\"><property name=\"visible\""
  ">True</property><property name=\"label\" translatable=\"yes\">&lt;i&gt;"
  "Transparent&lt;/i&gt;</property><property name=\"use_markup\">True</pro"
  "perty></object><packing><property name=\"expand\">False</property><prop"
  "erty name=\"fill\">False</property><property name=\"position\">0</prope"
  "rty></packing></child><child><object class=\"GtkHScale\" id=\"inactive_"
  "opacity_scale\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">True</property><property name=\"update_policy\">discont"
  "inuous</property><property name=\"adjustment\">adjustment3</property><p"
  "roperty name=\"restrict_to_fill_level\">False</property><property name="
  "\"draw_value\">False</property></object><packing><property name=\"posit"
  "ion\">1</property></packing></child><child><object class=\"GtkLabel\" i"
  "d=\"label20\"><property name=\"visible\">True</property><property name="
  "\"label\" translatable=\"yes\">&lt;i&gt;Opaque&lt;/i&gt;</property><pro"
  "perty name=\"use_markup\">True</property></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">False</property><"
  "property name=\"position\">2</property></packing></child></object></chi"
  "ld></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">False</property><property name=\"position\">7</property"
  "></packing></child><child><object class=\"GtkLabel\" id=\"label14\"><pr"
  "operty name=\"visible\">True</property><property name=\"xalign\">0</pro"
  "perty><property name=\"label\" translatable=\"yes\">Opacity of windows "
  "during _move:</property><property name=\"use_underline\">True</property"
  "><property name=\"mnemonic_widget\">move_opacity_scale</property></obje"
  "ct><packing><property name=\"expand\">False</property><property name=\""
  "fill\">False</property><property name=\"position\">8</property></packin"
  "g></child><child><object class=\"GtkAlignment\" id=\"alignment7\"><prop"
  "erty name=\"visible\">True</property><property name=\"top_padding\">2</"
  "property><property name=\"left_padding\">12</property><child><object cl"
  "ass=\"GtkHBox\" id=\"hbox5\"><property name=\"visible\">True</property>"
  "<child><object class=\"GtkLabel\" id=\"label21\"><property name=\"visib"
  "le\">True</property><property name=\"label\" translatable=\"yes\">&lt;i"
  "&gt;Transparent&lt;/i&gt;</property><property name=\"use_markup\">True<"
  "/property></object><packing><property name=\"expand\">False</property><"
  "property name=\"fill\">False</property><property name=\"position\">0</p"
  "roperty></packing></child><child><object class=\"GtkHScale\" id=\"move_"
  "opacity_scale\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">True</property><property name=\"update_policy\">discont"
  "inuous</property><property name=\"adjustment\">adjustment4</property><p"
  "roperty name=\"restrict_to_fill_level\">False</property><property name="
  "\"draw_value\">False</property></object><packing><property name=\"posit"
  "ion\">1</property></packing></child><child><object class=\"GtkLabel\" i"
  "d=\"label22\"><property name=\"visible\">True</property><property name="
  "\"label\" translatable=\"yes\">&lt;i&gt;Opaque&lt;/i&gt;</property><pro"
  "perty name=\"use_markup\">True</property></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">False</property><"
  "property name=\"position\">2</property></packing></child></object></chi"
  "ld></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">False</property><property name=\"position\">9</property"
  "></packing></child><child><object class=\"GtkLabel\" id=\"label15\"><pr"
  "operty name=\"visible\">True</property><property name=\"xalign\">0</pro"
  "perty><property name=\"label\" translatable=\"yes\">Opacity of windows "
  "during resi_ze:</property><property name=\"use_underline\">True</proper"
  "ty><property name=\"mnemonic_widget\">resize_opacity_scale</property></"
  "object><packing><property name=\"expand\">False</property><property nam"
  "e=\"fill\">False</property><property name=\"position\">10</property></p"
  "acking></child><child><object class=\"GtkAlignment\" id=\"alignment8\">"
  "<property name=\"visible\">True</property><property name=\"top_padding\""
  ">2</property><property name=\"left_padding\">12</property><child><objec"
  "t class=\"GtkHBox\" id=\"hbox6\"><property name=\"visible\">True</prope"
  "rty><child><object class=\"GtkLabel\" id=\"label23\"><property name=\"v"
  "isible\">True</property><property name=\"label\" translatable=\"yes\">&"
  "lt;i&gt;Transparent&lt;/i&gt;</property><property name=\"use_markup\">T"
  "rue</property></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"fill\">False</property><property name=\"position\">"
  "0</property></packing></child><child><object class=\"GtkHScale\" id=\"r"
  "esize_opacity_scale\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">True</property><property name=\"update_policy\">d"
  "iscontinuous</property><property name=\"adjustment\">adjustment5</prope"
  "rty><property name=\"restrict_to_fill_level\">False</property><property"
  " name=\"draw_value\">False</property></object><packing><property name=\""
  "position\">1</property></packing></child><child><object class=\"GtkLabe"
  "l\" id=\"label24\"><property name=\"visible\">True</property><property "
  "name=\"label\" translatable=\"yes\">&lt;i&gt;Opaque&lt;/i&gt;</property"
  "><property name=\"use_markup\">True</property></object><packing><proper"
  "ty name=\"expand\">False</property><property name=\"fill\">False</prope"
  "rty><property name=\"position\">2</property></packing></child></object>"
  "</child></object><packing><property name=\"expand\">False</property><pr"
  "operty name=\"fill\">False</property><property name=\"position\">11</pr"
  "operty></packing></child><child><object class=\"GtkLabel\" id=\"label16"
  "\"><property name=\"visible\">True</property><property name=\"xalign\">"
  "0</property><property name=\"label\" translatable=\"yes\">Opacity of po"
  "pup window_s:</property><property name=\"use_underline\">True</property"
  "><property name=\"mnemonic_widget\">popup_opacity_scale</property></obj"
  "ect><packing><property name=\"expand\">False</property><property name=\""
  "fill\">False</property><property name=\"position\">12</property></packi"
  "ng></child><child><object class=\"GtkAlignment\" id=\"alignment9\"><pro"
  "perty name=\"visible\">True</property><property name=\"top_padding\">2<"
  "/property><property name=\"left_padding\">12</property><child><object c"
  "lass=\"GtkHBox\" id=\"hbox7\"><property name=\"visible\">True</property"
  "><child><object class=\"GtkLabel\" id=\"label25\"><property name=\"visi"
  "ble\">True</property><property name=\"label\" translatable=\"yes\">&lt;"
  "i&gt;Transparent&lt;/i&gt;</property><property name=\"use_markup\">True"
  "</property></object><packing><property name=\"expand\">False</property>"
  "<property name=\"fill\">False</property><property name=\"position\">0</"
  "property></packing></child><child><object class=\"GtkHScale\" id=\"popu"
  "p_opacity_scale\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">True</property><property name=\"update_policy\">disco"
  "ntinuous</property><property name=\"adjustment\">adjustment6</property>"
  "<property name=\"restrict_to_fill_level\">False</property><property nam"
  "e=\"draw_value\">False</property></object><packing><property name=\"pos"
  "ition\">1</property></packing></child><child><object class=\"GtkLabel\""
  " id=\"label26\"><property name=\"visible\">True</property><property nam"
  "e=\"label\" translatable=\"yes\">&lt;i&gt;Opaque&lt;/i&gt;</property><p"
  "roperty name=\"use_markup\">True</property></object><packing><property "
  "name=\"expand\">False</property><property name=\"fill\">False</property"
  "><property name=\"position\">2</property></packing></child></object></c"
  "hild></object><packing><property name=\"expand\">False</property><prope"
  "rty name=\"fill\">False</property><property name=\"position\">13</prope"
  "rty></packing></child></object></child></object></child></object></chil"
  "d></object><packing><property name=\"position\">1</property></packing><"
  "/child></object><packing><property name=\"position\">5</property></pack"
  "ing></child><child type=\"tab\"><object class=\"GtkLabel\" id=\"label6\""
  "><property name=\"visible\">True</property><property name=\"label\" tra"
  "nslatable=\"yes\">C_ompositor</property><property name=\"use_underline\""
  ">True</property></object><packing><property name=\"position\">5</proper"
  "ty><property name=\"tab_fill\">False</property></packing></child></obje"
  "ct><packing><property name=\"position\">1</property></packing></child><"
  "child internal-child=\"action_area\"><object class=\"GtkHButtonBox\" id"
  "=\"dialog-action_area1\"><property name=\"visible\">True</property><pro"
  "perty name=\"layout_style\">end</property><child><object class=\"GtkBut"
  "ton\" id=\"button2\"><property name=\"label\">gtk-help</property><prope"
  "rty name=\"visible\">True</property><property name=\"sensitive\">False<"
  "/property><property name=\"can_focus\">True</property><property name=\""
  "receives_default\">True</property><property name=\"use_stock\">True</pr"
  "operty></object><packing><property name=\"expand\">False</property><pro"
  "perty name=\"fill\">False</property><property name=\"position\">0</prop"
  "erty><property name=\"secondary\">True</property></packing></child><chi"
  "ld><object class=\"GtkButton\" id=\"button1\"><property name=\"label\">"
  "gtk-close</property><property name=\"visible\">True</property><property"
  " name=\"can_focus\">True</property><property name=\"receives_default\">"
  "True</property><property name=\"use_stock\">True</property></object><pa"
  "cking><property name=\"expand\">False</property><property name=\"fill\""
  ">False</property><property name=\"position\">1</property></packing></ch"
  "ild></object><packing><property name=\"expand\">False</property><proper"
  "ty name=\"pack_type\">end</property><property name=\"position\">0</prop"
  "erty></packing></child></object></child><action-widgets><action-widget "
  "response=\"0\">button2</action-widget><action-widget response=\"0\">but"
  "ton1</action-widget></action-widgets></object></interface>"
};

static const unsigned tweaks_dialog_ui_length = 37210u;

